### PR TITLE
Add interfaces for HobknobClient and HobknobClientFactory

### PR DESCRIPTION
**Pull request by andyroyle**
to make injection (and mocking) easier

### CODE REVIEW

**Comment by andyroyle** [comment]
*nudge* @jankowiakmaria @matteofigus anybody still maintaining this library?

**Comment by pbazydlo** [comment]
@chriscartlidge can you take a look?

**Comment by chriscartlidge** [comment]
@andyroyle Apologies. LGTM 👍

**Comment by andyroyle** [comment]
cheers love

**Comment by andyroyle** [comment]
also, I just checked the Nuget page to see who has permissions to publish and found that it's only ex-OpenTablers. @chriscartlidge do you have a nuget account so I can give you permissions?

**Comment by chriscartlidge** [comment]
@andyroyle I do! Username: cjcartlidge .. Cheers dude.

**Pull request merged**
